
version: 2

models:
  - name: actors
    description: "Table containing actor information"
    columns:
      - name: actor_id
        description: "Primary key for the actors table"
        tests:
          - unique
          - not_null
      - name: actor_name
        description: "Actor name"
        tests:
          - not_null

  - name: film_actors
    description: "Table linking films and actors"
    columns:
      - name: film_id
        description: "Foreign key to the films table"
        tests:
          - not_null
      - name: actor_id
        description: "Foreign key to the actors table"
        tests:
          - not_null

  - name: films
    description: "Table containing film information"
    columns:
      - name: film_id
        description: "Primary key for the films table"
        tests:
          - unique
          - not_null
      - name: title
        description: "Title of the film"
        tests:
          - not_null
      - name: release_date
        description: "Release date of the film"
        tests:
          - not_null
      - name: price
        description: "Price of the film"
        tests:
          - not_null
      - name: rating
        description: "Rating of the film"
        tests:
          - not_null
      - name: user_rating
        description: "User rating of the film"
        tests:
          - not_null